export const FETCH_RESUME_EXPERIENCE_REQUEST = 'FETCH_RESUME_EXPERIENCE_REQUEST'
export const FETCH_RESUME_EXPERIENCE_SUCCESS = 'FETCH_RESUME_EXPERIENCE_SUCCESS'
export const FETCH_RESUME_EXPERIENCE_FAILURE = 'FETCH_RESUME_EXPERIENCE_FAILURE'

