export const FETCH_RESUME_HEADER_REQUEST = 'FETCH_RESUME_HEADER_REQUEST'
export const FETCH_RESUME_HEADER_SUCCESS = 'FETCH_RESUME_HEADER_SUCCESS'
export const FETCH_RESUME_HEADER_FAILURE = 'FETCH_RESUME_HEADER_FAILURE'

export const POST_RESUME_HEADER_REQUEST = 'POST_RESUME_HEADER_REQUEST'
export const POST_RESUME_HEADER_SUCCESS = 'POST_RESUME_HEADER_SUCCESS'
export const POST_RESUME_HEADER_FAILURE = 'POST_RESUME_HEADER_FAILURE'





