export const FETCH_RESUME_SUMMARY_REQUEST = 'FETCH_RESUME_SUMMARY_REQUEST'
export const FETCH_RESUME_SUMMARY_SUCCESS = 'FETCH_RESUME_SUMMARY_SUCCESS'
export const FETCH_RESUME_SUMMARY_FAILURE = 'FETCH_RESUME_SUMMARY_FAILURE'